name: Portfolio CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Check Python formatting with ruff
        run: ruff format --check .

      - name: Lint Python with ruff
        run: ruff check .

      - name: Run Python script
        run: python generate_portfolio.py

      - name: Install Prettier & Yamllint
        run: |
          npm install -g prettier
          pip install yamllint

      - name: Format and Lint YAML files
        run: yamllint portfolio.yml portfolio_example.yml .github/workflows/deploy.yml

      - name: Format and Lint HTML, JS, and CSS files
        run: prettier --check "**/*.{html,js,css}"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
